apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-3
  template:
    metadata:
      labels:
        app: nginx-3
    spec:
      containers:
      - name: nginx-3
        image: nginx:latest  # Using the latest official nginx-3 image
        ports:
        - containerPort: 80
        resources: {}
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: nginx-3-config
              key: message
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: nginx-3-secret
              key: secretkey
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-3-service
spec:
  selector:
    app: nginx-3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Change to NodePort or ClusterIP as needed
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-3-secret
type: Opaque
data:
  # Note: Values must be base64 encoded
  secretkey: c2VjcmV0VmFsdWU= # "secretValue" base64 encoded
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-3-config
data:
  message: "Hello, World from nginx-3 ConfigMap!"

